# @see https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: UTC
    versioning-strategy: increase
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-major]
      - dependency-name: pnpm
    groups:
      minor-and-patch:
        patterns: ['*']
        update-types: [minor, patch]
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: UTC
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-major]
    groups:
      minor-and-patch:
        patterns: ['*']
        update-types: [minor, patch]
    commit-message:
      prefix: chore
      include: scope
